//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaiPanLaManager {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FrmMgrMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmMgrMain() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaiPanLaManager.FrmMgrMain", typeof(FrmMgrMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool colAppID_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("colAppID.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool colAvatar_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("colAvatar.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool colCity_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("colCity.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool colCountry_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("colCountry.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool colCreateTime_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("colCreateTime.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool colExpire_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("colExpire.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool colGender_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("colGender.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool colID_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("colID.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool colMobile_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("colMobile.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool colNick_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("colNick.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool colNo_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("colNo.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool colOpenID_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("colOpenID.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool colProvince_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("colProvince.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        public static bool colSubType_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("colSubType.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=17,Y=17} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Point menuStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=368,Y=17} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Point statusStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=258,Y=17} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Point toolStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap toolStripButton1_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButton1.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap toolStripButton2_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButton2.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
