  INSERT INTO  [STG01_KAIPANLA].[DBO].[TBL_SUBSCRIBE]
  SELECT 
	[OPENID],
	[UNIONID],
	'free'AS [SUB_TYPE],
	DATEDIFF(S,'1970-01-01 08:00:00', DATEADD(DAY,7,GETDATE())) AS [SUB_EXPIRE] ,
	GETDATE() AS [CREATE_TIME]
  FROM [STG01_KAIPANLA].[DBO].[TBL_USER_INFO]
	WHERE [OPENID] NOT IN(
		SELECT [OPENID] 
		FROM  [STG01_KAIPANLA].[DBO].[TBL_SUBSCRIBE]
	)
 

   update [stg01_db].[dbo].[TBL_SUBSCRIBE]
  set CREATE_TIME =   GETDATE()
  where CREATE_TIME is null